# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bottle.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import QApplication, QWidget, QLabel, QListWidget, QListWidgetItem, QHBoxLayout
#import pp
from PyQt5.Qt import *
# from PyQt5.QtGui import QIcon ,  QBrush , QColor
# from PyQt5.QtCore import Qt
from PyQt5 import QtCore, QtGui, QtWidgets
import random

class bot(QWidget):
    def paintEvent(self, a: QtGui.QPaintEvent) -> None:
        painter9= QPainter(self)
        pixmap9 = QPixmap("bottle.jpg")
        painter9.drawPixmap(self.rect(), pixmap9)
    def __init__(self, parent=None):
        super(bot, self).__init__(parent)
        self.setObjectName("漂流瓶bottle")
        self.resize(420, 320)
        bottle = self
        self.bottle_txt = QtWidgets.QLabel(bottle)
        self.bottle_txt.setGeometry(QtCore.QRect(40, 40, 331, 121))
        self.bottle_txt.setStyleSheet("font: 10pt \"幼圆\";"
                                      "border:none;"
                                      "background-color:rgba(255,255,255,180);")
        self.bottle_txt.setObjectName("bottle_txt")
        self.drift_txt = QtWidgets.QTextEdit(bottle)
        self.drift_txt.setGeometry(QtCore.QRect(40, 180, 281, 51))
        self.drift_txt.setStyleSheet("font: 10pt \"幼圆\";"
                                      "border:none;"
                                      "background-color:rgba(255,255,255,180);")
        self.drift_txt.setObjectName("drift_txt")
        self.drift = QtWidgets.QPushButton(bottle)
        self.drift.setGeometry(QtCore.QRect(320, 180, 61, 51))
        self.drift.setStyleSheet("QPushButton{color:white}"
                                     "QPushButton{background-color:#576196}"
                                     "QPushButton{border:0px}"
                                     "QPushButton{border-radius:0px}"
                                     "QPushButton{padding:2px 4px}"
                                     "QPushButton{font:10pt\"幼圆\"}")
        self.drift.setObjectName("drift")

        self.changebot=QtWidgets.QPushButton(bottle)
        self.changebot.setGeometry(QtCore.QRect(280, 30, 90, 30))
        self.changebot.setStyleSheet("QPushButton{color:white}"
                                "QPushButton{background-color:#576196}"
                                "QPushButton{border:0px}"
                                "QPushButton{border-radius:5px}"
                                "QPushButton{padding:2px 4px}"
                                "QPushButton{font:11pt\"幼圆\"}")
        self.changebot.setObjectName("drift")
        self.changebot.setText('换个瓶子')

        #self.changebot.clicked.connect(self.change_bot)
        #self.drift.clicked.connect(self.drift_bot)


        self.retranslateUi(bottle)
        QtCore.QMetaObject.connectSlotsByName(bottle)
        self.chaeckbotid = QtWidgets.QPushButton(bottle)
        self.chaeckbotid.setGeometry(QtCore.QRect(180,30, 90, 30))
        self.chaeckbotid.setStyleSheet("QPushButton{color:white}"
                                     "QPushButton{background-color:#576196}"
                                     "QPushButton{border:0px}"
                                     "QPushButton{border-radius:5px}"
                                     "QPushButton{padding:2px 4px}"
                                     "QPushButton{font:11pt\"幼圆\"}")
        self.chaeckbotid.setObjectName("drift")
        self.chaeckbotid.setText('添加好友')

    def retranslateUi(self, bottle):
        _translate = QtCore.QCoreApplication.translate
        bottle.setWindowTitle(_translate("bottle", "漂流瓶"))
        self.bottle_txt.setText(_translate("bottle", "漂流瓶内容"))
        self.drift.setText(_translate("bottle", "扔瓶子"))
    def drift_bot(self):

        x=self.drift_txt.toPlainText()
        print(x)
        self.drift_txt.clear()
    def change_bot(self):
        x=[1,2,3,4,5,6,78,7,87,8,78,'hhhhhh','xswl','我爱上了lt','lt真棒嘻嘻嘻']
        y=random.sample(x, 1)
        self.bottle_txt.setText(str(y))
if __name__ == '__main__':
    app = QApplication(sys.argv)
    bot1=bot()
    bot1.show()
    sys.exit(app.exec_())
