from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import QApplication, QWidget, QLabel, QListWidget, QListWidgetItem, QHBoxLayout
from PyQt5.QtWidgets import QDialog, QMainWindow
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import QApplication, QWidget, QLabel, QListWidget, QListWidgetItem, QHBoxLayout
#import pp
from PyQt5 import QtCore, QtGui, QtWidgets
#from module.items import *
import pp
import os
import sys
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtCore import * 		# QSize
class  emot(QWidget):
    def __init__(self, parent=None):
        super( emot, self).__init__(parent)
        Form=self
        self.resize(540, 270)
        Form.setStyleSheet("")

        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 45, 45))
        self.pushButton.setObjectName("表情包")

        """self.pushButton2 = QtWidgets.QPushButton(Form)
        self.pushButton2.setGeometry(QtCore.QRect(45, 0, 45, 45))
        self.pushButton2.setObjectName("pushButton2")

        self.pushButton3 = QtWidgets.QPushButton(Form)
        self.pushButton3.setGeometry(QtCore.QRect(90, 0, 45, 45))
        self.pushButton3.setObjectName("pushButton")

        self.pushButton4 = QtWidgets.QPushButton(Form)
        self.pushButton4.setGeometry(QtCore.QRect(0, 0, 45, 45))
        self.pushButton4.setObjectName("pushButton")"""
        """for i in range(6):
            for j in range(12):
                x=i*12+j
                self.pushButton_x=QtWidgets.QPushButton(Form)
                self.pushButton_x.setGeometry(QtCore.QRect(j*45, i*45, 45, 45))
                self.pushButton_x.setObjectName(str(x))
                self.pushButton_x.setText("" )
                self.pushButton_x.setStyleSheet("border-image: url(:/emopho/"+str(x)+".jpg);")
                #print("E:/python_code/QT/pp/emopho/"+str(x)+".jpg);")
                self.pushButton_x.clicked.connect(lambda :self.R(x))"""

        self.pushButton_0=QtWidgets.QPushButton(Form)
        self.pushButton_0.setGeometry(QtCore.QRect(0*45, 0*45, 45, 45))
        self.pushButton_0.setObjectName(str(0))
        self.pushButton_0.setText("" )
        self.pushButton_0.setStyleSheet("border-image: url(:/emopho/"+str(0)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(0)+".jpg);")
        self.pushButton_0.clicked.connect(lambda :self.R(0))

        self.pushButton_1=QtWidgets.QPushButton(Form)
        self.pushButton_1.setGeometry(QtCore.QRect(1*45, 0*45, 45, 45))
        self.pushButton_1.setObjectName(str(1))
        self.pushButton_1.setText("" )
        self.pushButton_1.setStyleSheet("border-image: url(:/emopho/"+str(1)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(1)+".jpg);")
        self.pushButton_1.clicked.connect(lambda :self.R(1))

        self.pushButton_2=QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(2*45, 0*45, 45, 45))
        self.pushButton_2.setObjectName(str(2))
        self.pushButton_2.setText("" )
        self.pushButton_2.setStyleSheet("border-image: url(:/emopho/"+str(2)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(2)+".jpg);")
        self.pushButton_2.clicked.connect(lambda :self.R(2))

        self.pushButton_3=QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(3*45, 0*45, 45, 45))
        self.pushButton_3.setObjectName(str(3))
        self.pushButton_3.setText("" )
        self.pushButton_3.setStyleSheet("border-image: url(:/emopho/"+str(3)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(3)+".jpg);")
        self.pushButton_3.clicked.connect(lambda :self.R(3))

        self.pushButton_4=QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(4*45, 0*45, 45, 45))
        self.pushButton_4.setObjectName(str(4))
        self.pushButton_4.setText("" )
        self.pushButton_4.setStyleSheet("border-image: url(:/emopho/"+str(4)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(4)+".jpg);")
        self.pushButton_4.clicked.connect(lambda :self.R(4))

        self.pushButton_5=QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(5*45, 0*45, 45, 45))
        self.pushButton_5.setObjectName(str(5))
        self.pushButton_5.setText("" )
        self.pushButton_5.setStyleSheet("border-image: url(:/emopho/"+str(5)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(5)+".jpg);")
        self.pushButton_5.clicked.connect(lambda :self.R(5))

        self.pushButton_6=QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(6*45, 0*45, 45, 45))
        self.pushButton_6.setObjectName(str(6))
        self.pushButton_6.setText("" )
        self.pushButton_6.setStyleSheet("border-image: url(:/emopho/"+str(6)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(6)+".jpg);")
        self.pushButton_6.clicked.connect(lambda :self.R(6))

        self.pushButton_7=QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(7*45, 0*45, 45, 45))
        self.pushButton_7.setObjectName(str(7))
        self.pushButton_7.setText("" )
        self.pushButton_7.setStyleSheet("border-image: url(:/emopho/"+str(7)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(7)+".jpg);")
        self.pushButton_7.clicked.connect(lambda :self.R(7))

        self.pushButton_8=QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(8*45, 0*45, 45, 45))
        self.pushButton_8.setObjectName(str(8))
        self.pushButton_8.setText("" )
        self.pushButton_8.setStyleSheet("border-image: url(:/emopho/"+str(8)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(8)+".jpg);")
        self.pushButton_8.clicked.connect(lambda :self.R(8))

        self.pushButton_9=QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(9*45, 0*45, 45, 45))
        self.pushButton_9.setObjectName(str(9))
        self.pushButton_9.setText("" )
        self.pushButton_9.setStyleSheet("border-image: url(:/emopho/"+str(9)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(9)+".jpg);")
        self.pushButton_9.clicked.connect(lambda :self.R(9))

        self.pushButton_10=QtWidgets.QPushButton(Form)
        self.pushButton_10.setGeometry(QtCore.QRect(10*45, 0*45, 45, 45))
        self.pushButton_10.setObjectName(str(10))
        self.pushButton_10.setText("" )
        self.pushButton_10.setStyleSheet("border-image: url(:/emopho/"+str(10)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(10)+".jpg);")
        self.pushButton_10.clicked.connect(lambda :self.R(10))

        self.pushButton_11=QtWidgets.QPushButton(Form)
        self.pushButton_11.setGeometry(QtCore.QRect(11*45, 0*45, 45, 45))
        self.pushButton_11.setObjectName(str(11))
        self.pushButton_11.setText("" )
        self.pushButton_11.setStyleSheet("border-image: url(:/emopho/"+str(11)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(11)+".jpg);")
        self.pushButton_11.clicked.connect(lambda :self.R(11))

        self.pushButton_12=QtWidgets.QPushButton(Form)
        self.pushButton_12.setGeometry(QtCore.QRect(0*45, 1*45, 45, 45))
        self.pushButton_12.setObjectName(str(12))
        self.pushButton_12.setText("" )
        self.pushButton_12.setStyleSheet("border-image: url(:/emopho/"+str(12)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(12)+".jpg);")
        self.pushButton_12.clicked.connect(lambda :self.R(12))

        self.pushButton_13=QtWidgets.QPushButton(Form)
        self.pushButton_13.setGeometry(QtCore.QRect(1*45, 1*45, 45, 45))
        self.pushButton_13.setObjectName(str(13))
        self.pushButton_13.setText("" )
        self.pushButton_13.setStyleSheet("border-image: url(:/emopho/"+str(13)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(13)+".jpg);")
        self.pushButton_13.clicked.connect(lambda :self.R(13))

        self.pushButton_14=QtWidgets.QPushButton(Form)
        self.pushButton_14.setGeometry(QtCore.QRect(2*45, 1*45, 45, 45))
        self.pushButton_14.setObjectName(str(14))
        self.pushButton_14.setText("" )
        self.pushButton_14.setStyleSheet("border-image: url(:/emopho/"+str(14)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(14)+".jpg);")
        self.pushButton_14.clicked.connect(lambda :self.R(14))

        self.pushButton_15=QtWidgets.QPushButton(Form)
        self.pushButton_15.setGeometry(QtCore.QRect(3*45, 1*45, 45, 45))
        self.pushButton_15.setObjectName(str(15))
        self.pushButton_15.setText("" )
        self.pushButton_15.setStyleSheet("border-image: url(:/emopho/"+str(15)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(15)+".jpg);")
        self.pushButton_15.clicked.connect(lambda :self.R(15))

        self.pushButton_16=QtWidgets.QPushButton(Form)
        self.pushButton_16.setGeometry(QtCore.QRect(4*45, 1*45, 45, 45))
        self.pushButton_16.setObjectName(str(16))
        self.pushButton_16.setText("" )
        self.pushButton_16.setStyleSheet("border-image: url(:/emopho/"+str(16)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(16)+".jpg);")
        self.pushButton_16.clicked.connect(lambda :self.R(16))

        self.pushButton_17=QtWidgets.QPushButton(Form)
        self.pushButton_17.setGeometry(QtCore.QRect(5*45, 1*45, 45, 45))
        self.pushButton_17.setObjectName(str(17))
        self.pushButton_17.setText("" )
        self.pushButton_17.setStyleSheet("border-image: url(:/emopho/"+str(17)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(17)+".jpg);")
        self.pushButton_17.clicked.connect(lambda :self.R(17))

        self.pushButton_18=QtWidgets.QPushButton(Form)
        self.pushButton_18.setGeometry(QtCore.QRect(6*45, 1*45, 45, 45))
        self.pushButton_18.setObjectName(str(18))
        self.pushButton_18.setText("" )
        self.pushButton_18.setStyleSheet("border-image: url(:/emopho/"+str(18)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(18)+".jpg);")
        self.pushButton_18.clicked.connect(lambda :self.R(18))

        self.pushButton_19=QtWidgets.QPushButton(Form)
        self.pushButton_19.setGeometry(QtCore.QRect(7*45, 1*45, 45, 45))
        self.pushButton_19.setObjectName(str(19))
        self.pushButton_19.setText("" )
        self.pushButton_19.setStyleSheet("border-image: url(:/emopho/"+str(19)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(19)+".jpg);")
        self.pushButton_19.clicked.connect(lambda :self.R(19))

        self.pushButton_20=QtWidgets.QPushButton(Form)
        self.pushButton_20.setGeometry(QtCore.QRect(8*45, 1*45, 45, 45))
        self.pushButton_20.setObjectName(str(20))
        self.pushButton_20.setText("" )
        self.pushButton_20.setStyleSheet("border-image: url(:/emopho/"+str(20)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(20)+".jpg);")
        self.pushButton_20.clicked.connect(lambda :self.R(20))

        self.pushButton_21=QtWidgets.QPushButton(Form)
        self.pushButton_21.setGeometry(QtCore.QRect(9*45, 1*45, 45, 45))
        self.pushButton_21.setObjectName(str(21))
        self.pushButton_21.setText("" )
        self.pushButton_21.setStyleSheet("border-image: url(:/emopho/"+str(21)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(21)+".jpg);")
        self.pushButton_21.clicked.connect(lambda :self.R(21))

        self.pushButton_22=QtWidgets.QPushButton(Form)
        self.pushButton_22.setGeometry(QtCore.QRect(10*45, 1*45, 45, 45))
        self.pushButton_22.setObjectName(str(22))
        self.pushButton_22.setText("" )
        self.pushButton_22.setStyleSheet("border-image: url(:/emopho/"+str(22)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(22)+".jpg);")
        self.pushButton_22.clicked.connect(lambda :self.R(22))

        self.pushButton_23=QtWidgets.QPushButton(Form)
        self.pushButton_23.setGeometry(QtCore.QRect(11*45, 1*45, 45, 45))
        self.pushButton_23.setObjectName(str(23))
        self.pushButton_23.setText("" )
        self.pushButton_23.setStyleSheet("border-image: url(:/emopho/"+str(23)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(23)+".jpg);")
        self.pushButton_23.clicked.connect(lambda :self.R(23))

        self.pushButton_24=QtWidgets.QPushButton(Form)
        self.pushButton_24.setGeometry(QtCore.QRect(0*45, 2*45, 45, 45))
        self.pushButton_24.setObjectName(str(24))
        self.pushButton_24.setText("" )
        self.pushButton_24.setStyleSheet("border-image: url(:/emopho/"+str(24)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(24)+".jpg);")
        self.pushButton_24.clicked.connect(lambda :self.R(24))

        self.pushButton_25=QtWidgets.QPushButton(Form)
        self.pushButton_25.setGeometry(QtCore.QRect(1*45, 2*45, 45, 45))
        self.pushButton_25.setObjectName(str(25))
        self.pushButton_25.setText("" )
        self.pushButton_25.setStyleSheet("border-image: url(:/emopho/"+str(25)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(25)+".jpg);")
        self.pushButton_25.clicked.connect(lambda :self.R(25))

        self.pushButton_26=QtWidgets.QPushButton(Form)
        self.pushButton_26.setGeometry(QtCore.QRect(2*45, 2*45, 45, 45))
        self.pushButton_26.setObjectName(str(26))
        self.pushButton_26.setText("" )
        self.pushButton_26.setStyleSheet("border-image: url(:/emopho/"+str(26)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(26)+".jpg);")
        self.pushButton_26.clicked.connect(lambda :self.R(26))

        self.pushButton_27=QtWidgets.QPushButton(Form)
        self.pushButton_27.setGeometry(QtCore.QRect(3*45, 2*45, 45, 45))
        self.pushButton_27.setObjectName(str(27))
        self.pushButton_27.setText("" )
        self.pushButton_27.setStyleSheet("border-image: url(:/emopho/"+str(27)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(27)+".jpg);")
        self.pushButton_27.clicked.connect(lambda :self.R(27))

        self.pushButton_28=QtWidgets.QPushButton(Form)
        self.pushButton_28.setGeometry(QtCore.QRect(4*45, 2*45, 45, 45))
        self.pushButton_28.setObjectName(str(28))
        self.pushButton_28.setText("" )
        self.pushButton_28.setStyleSheet("border-image: url(:/emopho/"+str(28)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(28)+".jpg);")
        self.pushButton_28.clicked.connect(lambda :self.R(28))

        self.pushButton_29=QtWidgets.QPushButton(Form)
        self.pushButton_29.setGeometry(QtCore.QRect(5*45, 2*45, 45, 45))
        self.pushButton_29.setObjectName(str(29))
        self.pushButton_29.setText("" )
        self.pushButton_29.setStyleSheet("border-image: url(:/emopho/"+str(29)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(29)+".jpg);")
        self.pushButton_29.clicked.connect(lambda :self.R(29))

        self.pushButton_30=QtWidgets.QPushButton(Form)
        self.pushButton_30.setGeometry(QtCore.QRect(6*45, 2*45, 45, 45))
        self.pushButton_30.setObjectName(str(30))
        self.pushButton_30.setText("" )
        self.pushButton_30.setStyleSheet("border-image: url(:/emopho/"+str(30)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(30)+".jpg);")
        self.pushButton_30.clicked.connect(lambda :self.R(30))

        self.pushButton_31=QtWidgets.QPushButton(Form)
        self.pushButton_31.setGeometry(QtCore.QRect(7*45, 2*45, 45, 45))
        self.pushButton_31.setObjectName(str(31))
        self.pushButton_31.setText("" )
        self.pushButton_31.setStyleSheet("border-image: url(:/emopho/"+str(31)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(31)+".jpg);")
        self.pushButton_31.clicked.connect(lambda :self.R(31))

        self.pushButton_32=QtWidgets.QPushButton(Form)
        self.pushButton_32.setGeometry(QtCore.QRect(8*45, 2*45, 45, 45))
        self.pushButton_32.setObjectName(str(32))
        self.pushButton_32.setText("" )
        self.pushButton_32.setStyleSheet("border-image: url(:/emopho/"+str(32)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(32)+".jpg);")
        self.pushButton_32.clicked.connect(lambda :self.R(32))

        self.pushButton_33=QtWidgets.QPushButton(Form)
        self.pushButton_33.setGeometry(QtCore.QRect(9*45, 2*45, 45, 45))
        self.pushButton_33.setObjectName(str(33))
        self.pushButton_33.setText("" )
        self.pushButton_33.setStyleSheet("border-image: url(:/emopho/"+str(33)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(33)+".jpg);")
        self.pushButton_33.clicked.connect(lambda :self.R(33))

        self.pushButton_34=QtWidgets.QPushButton(Form)
        self.pushButton_34.setGeometry(QtCore.QRect(10*45, 2*45, 45, 45))
        self.pushButton_34.setObjectName(str(34))
        self.pushButton_34.setText("" )
        self.pushButton_34.setStyleSheet("border-image: url(:/emopho/"+str(34)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(34)+".jpg);")
        self.pushButton_34.clicked.connect(lambda :self.R(34))

        self.pushButton_35=QtWidgets.QPushButton(Form)
        self.pushButton_35.setGeometry(QtCore.QRect(11*45, 2*45, 45, 45))
        self.pushButton_35.setObjectName(str(35))
        self.pushButton_35.setText("" )
        self.pushButton_35.setStyleSheet("border-image: url(:/emopho/"+str(35)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(35)+".jpg);")
        self.pushButton_35.clicked.connect(lambda :self.R(35))

        self.pushButton_36=QtWidgets.QPushButton(Form)
        self.pushButton_36.setGeometry(QtCore.QRect(0*45, 3*45, 45, 45))
        self.pushButton_36.setObjectName(str(36))
        self.pushButton_36.setText("" )
        self.pushButton_36.setStyleSheet("border-image: url(:/emopho/"+str(36)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(36)+".jpg);")
        self.pushButton_36.clicked.connect(lambda :self.R(36))

        self.pushButton_37=QtWidgets.QPushButton(Form)
        self.pushButton_37.setGeometry(QtCore.QRect(1*45, 3*45, 45, 45))
        self.pushButton_37.setObjectName(str(37))
        self.pushButton_37.setText("" )
        self.pushButton_37.setStyleSheet("border-image: url(:/emopho/"+str(37)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(37)+".jpg);")
        self.pushButton_37.clicked.connect(lambda :self.R(37))

        self.pushButton_38=QtWidgets.QPushButton(Form)
        self.pushButton_38.setGeometry(QtCore.QRect(2*45, 3*45, 45, 45))
        self.pushButton_38.setObjectName(str(38))
        self.pushButton_38.setText("" )
        self.pushButton_38.setStyleSheet("border-image: url(:/emopho/"+str(38)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(38)+".jpg);")
        self.pushButton_38.clicked.connect(lambda :self.R(38))

        self.pushButton_39=QtWidgets.QPushButton(Form)
        self.pushButton_39.setGeometry(QtCore.QRect(3*45, 3*45, 45, 45))
        self.pushButton_39.setObjectName(str(39))
        self.pushButton_39.setText("" )
        self.pushButton_39.setStyleSheet("border-image: url(:/emopho/"+str(39)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(39)+".jpg);")
        self.pushButton_39.clicked.connect(lambda :self.R(39))

        self.pushButton_40=QtWidgets.QPushButton(Form)
        self.pushButton_40.setGeometry(QtCore.QRect(4*45, 3*45, 45, 45))
        self.pushButton_40.setObjectName(str(40))
        self.pushButton_40.setText("" )
        self.pushButton_40.setStyleSheet("border-image: url(:/emopho/"+str(40)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(40)+".jpg);")
        self.pushButton_40.clicked.connect(lambda :self.R(40))

        self.pushButton_41=QtWidgets.QPushButton(Form)
        self.pushButton_41.setGeometry(QtCore.QRect(5*45, 3*45, 45, 45))
        self.pushButton_41.setObjectName(str(41))
        self.pushButton_41.setText("" )
        self.pushButton_41.setStyleSheet("border-image: url(:/emopho/"+str(41)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(41)+".jpg);")
        self.pushButton_41.clicked.connect(lambda :self.R(41))

        self.pushButton_42=QtWidgets.QPushButton(Form)
        self.pushButton_42.setGeometry(QtCore.QRect(6*45, 3*45, 45, 45))
        self.pushButton_42.setObjectName(str(42))
        self.pushButton_42.setText("" )
        self.pushButton_42.setStyleSheet("border-image: url(:/emopho/"+str(42)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(42)+".jpg);")
        self.pushButton_42.clicked.connect(lambda :self.R(42))

        self.pushButton_43=QtWidgets.QPushButton(Form)
        self.pushButton_43.setGeometry(QtCore.QRect(7*45, 3*45, 45, 45))
        self.pushButton_43.setObjectName(str(43))
        self.pushButton_43.setText("" )
        self.pushButton_43.setStyleSheet("border-image: url(:/emopho/"+str(43)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(43)+".jpg);")
        self.pushButton_43.clicked.connect(lambda :self.R(43))

        self.pushButton_44=QtWidgets.QPushButton(Form)
        self.pushButton_44.setGeometry(QtCore.QRect(8*45, 3*45, 45, 45))
        self.pushButton_44.setObjectName(str(44))
        self.pushButton_44.setText("" )
        self.pushButton_44.setStyleSheet("border-image: url(:/emopho/"+str(44)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(44)+".jpg);")
        self.pushButton_44.clicked.connect(lambda :self.R(44))

        self.pushButton_45=QtWidgets.QPushButton(Form)
        self.pushButton_45.setGeometry(QtCore.QRect(9*45, 3*45, 45, 45))
        self.pushButton_45.setObjectName(str(45))
        self.pushButton_45.setText("" )
        self.pushButton_45.setStyleSheet("border-image: url(:/emopho/"+str(45)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(45)+".jpg);")
        self.pushButton_45.clicked.connect(lambda :self.R(45))

        self.pushButton_46=QtWidgets.QPushButton(Form)
        self.pushButton_46.setGeometry(QtCore.QRect(10*45, 3*45, 45, 45))
        self.pushButton_46.setObjectName(str(46))
        self.pushButton_46.setText("" )
        self.pushButton_46.setStyleSheet("border-image: url(:/emopho/"+str(46)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(46)+".jpg);")
        self.pushButton_46.clicked.connect(lambda :self.R(46))

        self.pushButton_47=QtWidgets.QPushButton(Form)
        self.pushButton_47.setGeometry(QtCore.QRect(11*45, 3*45, 45, 45))
        self.pushButton_47.setObjectName(str(47))
        self.pushButton_47.setText("" )
        self.pushButton_47.setStyleSheet("border-image: url(:/emopho/"+str(47)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(47)+".jpg);")
        self.pushButton_47.clicked.connect(lambda :self.R(47))

        self.pushButton_48=QtWidgets.QPushButton(Form)
        self.pushButton_48.setGeometry(QtCore.QRect(0*45, 4*45, 45, 45))
        self.pushButton_48.setObjectName(str(48))
        self.pushButton_48.setText("" )
        self.pushButton_48.setStyleSheet("border-image: url(:/emopho/"+str(48)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(48)+".jpg);")
        self.pushButton_48.clicked.connect(lambda :self.R(48))

        self.pushButton_49=QtWidgets.QPushButton(Form)
        self.pushButton_49.setGeometry(QtCore.QRect(1*45, 4*45, 45, 45))
        self.pushButton_49.setObjectName(str(49))
        self.pushButton_49.setText("" )
        self.pushButton_49.setStyleSheet("border-image: url(:/emopho/"+str(49)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(49)+".jpg);")
        self.pushButton_49.clicked.connect(lambda :self.R(49))

        self.pushButton_50=QtWidgets.QPushButton(Form)
        self.pushButton_50.setGeometry(QtCore.QRect(2*45, 4*45, 45, 45))
        self.pushButton_50.setObjectName(str(50))
        self.pushButton_50.setText("" )
        self.pushButton_50.setStyleSheet("border-image: url(:/emopho/"+str(50)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(50)+".jpg);")
        self.pushButton_50.clicked.connect(lambda :self.R(50))

        self.pushButton_51=QtWidgets.QPushButton(Form)
        self.pushButton_51.setGeometry(QtCore.QRect(3*45, 4*45, 45, 45))
        self.pushButton_51.setObjectName(str(51))
        self.pushButton_51.setText("" )
        self.pushButton_51.setStyleSheet("border-image: url(:/emopho/"+str(51)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(51)+".jpg);")
        self.pushButton_51.clicked.connect(lambda :self.R(51))

        self.pushButton_52=QtWidgets.QPushButton(Form)
        self.pushButton_52.setGeometry(QtCore.QRect(4*45, 4*45, 45, 45))
        self.pushButton_52.setObjectName(str(52))
        self.pushButton_52.setText("" )
        self.pushButton_52.setStyleSheet("border-image: url(:/emopho/"+str(52)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(52)+".jpg);")
        self.pushButton_52.clicked.connect(lambda :self.R(52))

        self.pushButton_53=QtWidgets.QPushButton(Form)
        self.pushButton_53.setGeometry(QtCore.QRect(5*45, 4*45, 45, 45))
        self.pushButton_53.setObjectName(str(53))
        self.pushButton_53.setText("" )
        self.pushButton_53.setStyleSheet("border-image: url(:/emopho/"+str(53)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(53)+".jpg);")
        self.pushButton_53.clicked.connect(lambda :self.R(53))

        self.pushButton_54=QtWidgets.QPushButton(Form)
        self.pushButton_54.setGeometry(QtCore.QRect(6*45, 4*45, 45, 45))
        self.pushButton_54.setObjectName(str(54))
        self.pushButton_54.setText("" )
        self.pushButton_54.setStyleSheet("border-image: url(:/emopho/"+str(54)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(54)+".jpg);")
        self.pushButton_54.clicked.connect(lambda :self.R(54))

        self.pushButton_55=QtWidgets.QPushButton(Form)
        self.pushButton_55.setGeometry(QtCore.QRect(7*45, 4*45, 45, 45))
        self.pushButton_55.setObjectName(str(55))
        self.pushButton_55.setText("" )
        self.pushButton_55.setStyleSheet("border-image: url(:/emopho/"+str(55)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(55)+".jpg);")
        self.pushButton_55.clicked.connect(lambda :self.R(55))

        self.pushButton_56=QtWidgets.QPushButton(Form)
        self.pushButton_56.setGeometry(QtCore.QRect(8*45, 4*45, 45, 45))
        self.pushButton_56.setObjectName(str(56))
        self.pushButton_56.setText("" )
        self.pushButton_56.setStyleSheet("border-image: url(:/emopho/"+str(56)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(56)+".jpg);")
        self.pushButton_56.clicked.connect(lambda :self.R(56))

        self.pushButton_57=QtWidgets.QPushButton(Form)
        self.pushButton_57.setGeometry(QtCore.QRect(9*45, 4*45, 45, 45))
        self.pushButton_57.setObjectName(str(57))
        self.pushButton_57.setText("" )
        self.pushButton_57.setStyleSheet("border-image: url(:/emopho/"+str(57)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(57)+".jpg);")
        self.pushButton_57.clicked.connect(lambda :self.R(57))

        self.pushButton_58=QtWidgets.QPushButton(Form)
        self.pushButton_58.setGeometry(QtCore.QRect(10*45, 4*45, 45, 45))
        self.pushButton_58.setObjectName(str(58))
        self.pushButton_58.setText("" )
        self.pushButton_58.setStyleSheet("border-image: url(:/emopho/"+str(58)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(58)+".jpg);")
        self.pushButton_58.clicked.connect(lambda :self.R(58))

        self.pushButton_59=QtWidgets.QPushButton(Form)
        self.pushButton_59.setGeometry(QtCore.QRect(11*45, 4*45, 45, 45))
        self.pushButton_59.setObjectName(str(59))
        self.pushButton_59.setText("" )
        self.pushButton_59.setStyleSheet("border-image: url(:/emopho/"+str(59)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(59)+".jpg);")
        self.pushButton_59.clicked.connect(lambda :self.R(59))

        self.pushButton_60=QtWidgets.QPushButton(Form)
        self.pushButton_60.setGeometry(QtCore.QRect(0*45, 5*45, 45, 45))
        self.pushButton_60.setObjectName(str(60))
        self.pushButton_60.setText("" )
        self.pushButton_60.setStyleSheet("border-image: url(:/emopho/"+str(60)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(60)+".jpg);")
        self.pushButton_60.clicked.connect(lambda :self.R(60))

        self.pushButton_61=QtWidgets.QPushButton(Form)
        self.pushButton_61.setGeometry(QtCore.QRect(1*45, 5*45, 45, 45))
        self.pushButton_61.setObjectName(str(61))
        self.pushButton_61.setText("" )
        self.pushButton_61.setStyleSheet("border-image: url(:/emopho/"+str(61)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(61)+".jpg);")
        self.pushButton_61.clicked.connect(lambda :self.R(61))

        self.pushButton_62=QtWidgets.QPushButton(Form)
        self.pushButton_62.setGeometry(QtCore.QRect(2*45, 5*45, 45, 45))
        self.pushButton_62.setObjectName(str(62))
        self.pushButton_62.setText("" )
        self.pushButton_62.setStyleSheet("border-image: url(:/emopho/"+str(62)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(62)+".jpg);")
        self.pushButton_62.clicked.connect(lambda :self.R(62))

        self.pushButton_63=QtWidgets.QPushButton(Form)
        self.pushButton_63.setGeometry(QtCore.QRect(3*45, 5*45, 45, 45))
        self.pushButton_63.setObjectName(str(63))
        self.pushButton_63.setText("" )
        self.pushButton_63.setStyleSheet("border-image: url(:/emopho/"+str(63)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(63)+".jpg);")
        self.pushButton_63.clicked.connect(lambda :self.R(63))

        self.pushButton_64=QtWidgets.QPushButton(Form)
        self.pushButton_64.setGeometry(QtCore.QRect(4*45, 5*45, 45, 45))
        self.pushButton_64.setObjectName(str(64))
        self.pushButton_64.setText("" )
        self.pushButton_64.setStyleSheet("border-image: url(:/emopho/"+str(64)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(64)+".jpg);")
        self.pushButton_64.clicked.connect(lambda :self.R(64))

        self.pushButton_65=QtWidgets.QPushButton(Form)
        self.pushButton_65.setGeometry(QtCore.QRect(5*45, 5*45, 45, 45))
        self.pushButton_65.setObjectName(str(65))
        self.pushButton_65.setText("" )
        self.pushButton_65.setStyleSheet("border-image: url(:/emopho/"+str(65)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(65)+".jpg);")
        self.pushButton_65.clicked.connect(lambda :self.R(65))

        self.pushButton_66=QtWidgets.QPushButton(Form)
        self.pushButton_66.setGeometry(QtCore.QRect(6*45, 5*45, 45, 45))
        self.pushButton_66.setObjectName(str(66))
        self.pushButton_66.setText("" )
        self.pushButton_66.setStyleSheet("border-image: url(:/emopho/"+str(66)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(66)+".jpg);")
        self.pushButton_66.clicked.connect(lambda :self.R(66))

        self.pushButton_67=QtWidgets.QPushButton(Form)
        self.pushButton_67.setGeometry(QtCore.QRect(7*45, 5*45, 45, 45))
        self.pushButton_67.setObjectName(str(67))
        self.pushButton_67.setText("" )
        self.pushButton_67.setStyleSheet("border-image: url(:/emopho/"+str(67)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(67)+".jpg);")
        self.pushButton_67.clicked.connect(lambda :self.R(67))

        self.pushButton_68=QtWidgets.QPushButton(Form)
        self.pushButton_68.setGeometry(QtCore.QRect(8*45, 5*45, 45, 45))
        self.pushButton_68.setObjectName(str(68))
        self.pushButton_68.setText("" )
        self.pushButton_68.setStyleSheet("border-image: url(:/emopho/"+str(68)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(68)+".jpg);")
        self.pushButton_68.clicked.connect(lambda :self.R(68))

        self.pushButton_69=QtWidgets.QPushButton(Form)
        self.pushButton_69.setGeometry(QtCore.QRect(9*45, 5*45, 45, 45))
        self.pushButton_69.setObjectName(str(69))
        self.pushButton_69.setText("" )
        self.pushButton_69.setStyleSheet("border-image: url(:/emopho/"+str(69)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(69)+".jpg);")
        self.pushButton_69.clicked.connect(lambda :self.R(69))

        self.pushButton_70=QtWidgets.QPushButton(Form)
        self.pushButton_70.setGeometry(QtCore.QRect(10*45, 5*45, 45, 45))
        self.pushButton_70.setObjectName(str(70))
        self.pushButton_70.setText("" )
        self.pushButton_70.setStyleSheet("border-image: url(:/emopho/"+str(70)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(70)+".jpg);")
        self.pushButton_70.clicked.connect(lambda :self.R(70))

        self.pushButton_71=QtWidgets.QPushButton(Form)
        self.pushButton_71.setGeometry(QtCore.QRect(11*45, 5*45, 45, 45))
        self.pushButton_71.setObjectName(str(71))
        self.pushButton_71.setText("" )
        self.pushButton_71.setStyleSheet("border-image: url(:/emopho/"+str(71)+".jpg);")
        #print("E:/python_code/QT/pp/emopho/"+str(71)+".jpg);")
        self.pushButton_71.clicked.connect(lambda :self.R(71))


    def R(self,x):
        print(x)
        return x



import sys
if __name__ == "__main__":
    app=QtWidgets.QApplication(sys.argv)
    chat1=emot()
    chat1.show()
    sys.exit(app.exec_())