# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'find_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import QApplication, QWidget, QLabel, QListWidget, QListWidgetItem, QHBoxLayout
#import pp
from PyQt5.Qt import *
from PyQt5 import QtCore, QtGui, QtWidgets
from Global import globalmanager
class find2(QWidget):
    def paintEvent(self, a: QtGui.QPaintEvent) -> None:
        painter7 = QPainter(self)
        if globalmanager.flag_zt==1:
            pixmap7 = QPixmap("背景_5.jpg")
        else:
            pixmap7 = QPixmap("背景_05.jpg")
        painter7.drawPixmap(self.rect(), pixmap7)
    def __init__(self):
        super(find2, self).__init__()
        self.resize(400, 300)
        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setGeometry(QtCore.QRect(50, 80, 100, 30))
        self.label_2.setStyleSheet("font: 13pt \"幼圆\";")
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self)
        self.label_4.setGeometry(QtCore.QRect(50, 160, 100, 30))
        self.label_4.setObjectName("label_4")
        self.label_4.setStyleSheet("font: 13pt \"幼圆\";")
        self.find_ask = QtWidgets.QLineEdit(self)
        self.find_ask.setEnabled(True)
        self.find_ask.setGeometry(QtCore.QRect(180, 80, 151, 30))
        self.find_ask.setStyleSheet("font: 13pt \"幼圆\";"
                                    "border:none;"
                                    "background-color:rgba(255,255,255,150);")
        self.find_ask.setObjectName("find_ask")
        self.find_answer = QtWidgets.QLineEdit(self)
        self.find_answer.setGeometry(QtCore.QRect(180, 160, 151, 30))
        self.find_answer.setObjectName("find_answer")
        self.find_conBtn = QtWidgets.QPushButton(self)
        self.find_conBtn.setGeometry(QtCore.QRect(160, 230, 75, 30))
        self.find_conBtn.setObjectName("find_conBtn")
        self.find_canBtn = QtWidgets.QPushButton(self)
        self.find_canBtn.setGeometry(QtCore.QRect(290, 230, 75, 30))
        self.find_canBtn.setObjectName("find_canBtn")

        self.setWindowTitle("请输入密保答案以获取密码")
        self.label_2.setText("密保问题")
        self.label_4.setText("密保答案")
        self.find_answer.setPlaceholderText("请输入您的密保答案")
        self.find_answer.setStyleSheet("font: 9pt \"幼圆\";"
                                       "border:none;"
                                       "background-color:rgba(255,255,255,150);"
                                       )
        self.find_conBtn.setText("确定")
        self.find_conBtn.setStyleSheet("QPushButton{color:white}"
                                       "QPushButton:hover{color:blue}"
                                       "QPushButton{background-color:#000115}"
                                       "QPushButton{border:0px}"
                                       "QPushButton{border-radius:5px}"
                                       "QPushButton{padding:2px 4px}"
                                       "QPushButton{font:13pt\"幼圆\"}")
        self.find_canBtn.setText("取消")
        self.find_canBtn.setStyleSheet("QPushButton{color:white}"
                                       "QPushButton:hover{color:blue}"
                                       "QPushButton{background-color:#000115}"
                                       "QPushButton{border:0px}"
                                       "QPushButton{border-radius:5px}"
                                       "QPushButton{padding:2px 4px}"
                                       "QPushButton{font:13pt\"幼圆\"}")
import sys
if __name__ == "__main__":
    app=QtWidgets.QApplication(sys.argv)
    MainWindow=QtWidgets.QMainWindow()
    globalmanager.set_value1(2)
    ui=find2()
    ui.show()

    sys.exit(app.exec_())