# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Find.1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtGui import QPixmap
from PyQt5.QtWidgets import QApplication, QWidget, QLabel, QListWidget, QListWidgetItem, QHBoxLayout
#import pp
from PyQt5.Qt import *
from PyQt5 import QtCore, QtGui, QtWidgets
from Global import globalmanager
class find(QWidget):
    def paintEvent(self, a: QtGui.QPaintEvent) -> None:
        painter6 = QPainter(self)
        if globalmanager.flag_zt==1:
            pixmap6 = QPixmap("背景_4.jpg")
        else:
            pixmap6=QPixmap("背景_04.jpg")
        painter6.drawPixmap(self.rect(), pixmap6)
    def __init__(self):
        super(find, self).__init__()
        self.resize(366, 300)

        self.find_name = QtWidgets.QLineEdit(self)
        self.find_name.setGeometry(QtCore.QRect(140, 120, 151, 30))
        self.find_name.setObjectName("find_name")

        self.find_conBtn = QtWidgets.QPushButton(self)
        self.find_conBtn.setGeometry(QtCore.QRect(140, 240, 75, 30))
        self.find_conBtn.setObjectName("find_conBtn")
        self.label = QtWidgets.QLabel(self)
        self.label.setGeometry(QtCore.QRect(50, 120, 72, 30))
        self.label.setObjectName("label")
        self.label.setStyleSheet("font: 13pt \"幼圆\";")
        self.find_canBtn = QtWidgets.QPushButton(self)
        self.find_canBtn.setGeometry(QtCore.QRect(250, 240, 75, 30))
        self.find_canBtn.setObjectName("find_canBtn")

        self.setWindowTitle("请输入您的工号")
        self.find_name.setPlaceholderText( "请输入您的工号")
        self.find_name.setStyleSheet("font: 10pt \"幼圆\";"
                                     "border:none;"
                                     "background-color:rgba(255,255,255,150);")

        self.find_conBtn.setText( "确定")
        self.find_conBtn.setStyleSheet("QPushButton{color:white}"
                                          "QPushButton:hover{color:blue}"
                                          "QPushButton{background-color:#000115}"
                                          "QPushButton{border:0px}"
                                          "QPushButton{border-radius:5px}"
                                          "QPushButton{padding:2px 4px}"
                                          "QPushButton{font:13pt\"幼圆\"}")
        self.label.setText("工号")
        self.find_canBtn.setText("取消")
        self.find_canBtn.setStyleSheet("QPushButton{color:white}"
                                       "QPushButton:hover{color:blue}"
                                       "QPushButton{background-color:#000115}"
                                       "QPushButton{border:0px}"
                                       "QPushButton{border-radius:5px}"
                                       "QPushButton{padding:2px 4px}"
                                       "QPushButton{font:13pt\"幼圆\"}")



import sys
if __name__ == "__main__":
    app=QtWidgets.QApplication(sys.argv)
    MainWindow=QtWidgets.QMainWindow()
    globalmanager.set_value1(2)
    ui=find()
    ui.show()

    sys.exit(app.exec_())
