# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'warning.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.warn_label = QtWidgets.QLabel(Dialog)
        self.warn_label.setGeometry(QtCore.QRect(70, 50, 331, 131))
        self.warn_label.setObjectName("warn_label")
        self.warn_conBtn = QtWidgets.QPushButton(Dialog)
        self.warn_conBtn.setGeometry(QtCore.QRect(230, 230, 93, 28))
        self.warn_conBtn.setObjectName("warn_conBtn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Warning"))
        self.warn_label.setText(_translate("Dialog", "Warning:\n"
"     The password does not match the \n"
"confirmation password"))
        self.warn_conBtn.setText(_translate("Dialog", "确认"))
